### ISSUE TITLE
createOrder update onClick

### ISSUE THREAD

**Issue by ThatGuyMichael** [paypal/paypal-smart-payment-buttons#10]
I see that the onClick option is available which i'm using to perform some validations. However, I came across a situation where I need to update the payment amount in the purchase_units for the createOrder function after the button has render (guests are able to do partial payment). The onClick seems like the perfect time to update it after performing some validations. Is there some way of achieving that with the current smart button?

Also, is there an option for the onClick to pass parameters? The reason why, goes back to angular and being able to access the scope.

**Comment by bluepnume** [comment]
Can you please re-open over at https://github.com/paypal/paypal-checkout-components/issues

If you need to recalculate the amount, please do it in `createOrder`
