### ISSUE TITLE
Disabling/Enabling button

### ISSUE THREAD

**Issue by ThatGuyMichael** [paypal/paypal-smart-payment-buttons#11]
I already saw this closed issue for button validations : https://github.com/paypal/paypal-smart-payment-buttons/issues/3

However, that solution isn't really optimal in my case since payments amounts can change while the button is rendered (we allow partial payment and want the button to be visible so guest are aware). I already have validations for all the fields in java script and seems hackish in my case to create element's on the page just for PayPal to monitor for an event(s) vs just using java script (angular in my case) to directly change the disable state since that's where the bulk of my validation is done. I was looking for something like the below to be implemented.

First I'll create a button and store in a variable, then render it:
```
var payPalButton = paypal.Buttons();
payPalButton.render();
```

Later on, a validation error occurs on the UI, so I would call the disable function:

`payPalButton.disable();`

Later on when there's no validation error, i'll re-enable it:

`payPalButton.enable();
`

**Comment by bluepnume** [comment]
please see: https://developer.paypal.com/docs/checkout/integration-features/validation/
