### ISSUE TITLE
Validation with new smart buttons

### ISSUE THREAD

**Issue by gilesbutler** [paypal/paypal-smart-payment-buttons#3]
Hey Guys,

Am I right in thinking that this is the library that has replaced the old [checkout.js](https://github.com/paypal/paypal-checkout-components) library?

<img width="966" alt="screenshot 2019-02-08 at 14 14 44" src="https://user-images.githubusercontent.com/790734/52457079-1e0c4280-2bac-11e9-8f62-ea12d3e87a4b.png">

I'm trying to validate a clients form before submitting to PayPal...

<img width="520" alt="screenshot 2019-02-08 at 14 17 17" src="https://user-images.githubusercontent.com/790734/52457107-45fba600-2bac-11e9-900b-34748ebc24ed.png">

But I can't figure out the best approach, or any approach really. The old library had a `validate` method which we could use to validate forms before submitting to PayPal but it seems to have gone after looking at the source code.

Also how are we supposed to send customer address details etc through with this library? The [docs](https://developer.paypal.com/docs/checkout/best-practices/pass-accurate-info/) say to pass accurate billing and shipping info through but I can't see how.

Am I missing something? Maybe using the wrong library or something?

Thanks

**Comment by bluepnume** [comment]
We're planning to overhaul `validate` to allow asynchronous validation, which wasn't enabled before. Hopefully should have something out in the next week or two.

For now here's an example of validation using the old script: https://developer.paypal.com/demo/checkout/#/pattern/validation

**Comment by gilesbutler** [comment]
Thanks for the quick reply and for the info @bluepnume 👍

Yeah I came across that link on my travels. I think we'll have to go with that as this project is due in a few days. Good luck with the async work.

**Comment by gilesbutler** [comment]
Hey @bluepnume,

Any update on the validation work? 

Also fyi the link you sent doesn't show any validation examples anymore, seems like it's been removed from the docs.

**Comment by bluepnume** [comment]
I have a new doc staged for the next release of the developer.paypal.com docs. I'm pasting it here if you'd like to test it out, but **please treat this as a potentially unstable api until the main doc is released**. It should be good enough for local testing at the moment though, and if you find any bugs, please let me know:

-----

Sometimes it is necessary to run validation when the PayPal buttons are clicked. For example, your page may contain a web form, which needs to be valid before the transaction can be iniated.

For an optimal buyer experience, PayPal recommends doing as much of this validation as possible up-front, prior to rendering the buttons.

For any validation which can not be done up-front, follow this guide to run validation on click of the PayPal buttons.

## Synchronous validation

Whenever possible, PayPal recommends setting up synchronous validation for your page. This results in the best possible user experience: the buyer will see instantaneous feedback, and no popup window will be displayed.

```html
<p id="error" class="hidden">Please check the checkbox</p>
<label><input id="check" type="checkbox"> Check here to continue</label>

<script>
  paypal.Buttons({

    // onInit will be called when the button is first rendered
    onInit: function(data, actions) {

      // Disable the buttons
      actions.disable();

      // Listen for changes to the checkbox
      document.querySelector('#check')
        .addEventListener('change', function(event) {

          // Enable or disable the button when it is checked or unchecked
          if (event.target.checked) {
            actions.enable();
          } else {
            actions.disable();
          }
        });
    },

    // onClick will be called any time the button is clicked
    onClick: function() {

      // Show a validation error if the checkbox is not checked
      if (!document.querySelector('#check').checked) {
        document.querySelector('#error').classList.remove('hidden');
      }
    }

  }).render('#paypal-button-container');
</script>
```

## Asynchronous validation

Some validation must be done on the server-side, or via an asynchronous channel. This approach demonstrates how to run asynchonous validation on click of the button.

Do not use this approach for any validation which can be done synchronously, as it degrades the buyer's experience.

```html
<p id="error" class="hidden">Please check your information to continue</p>

<script>
  paypal.Buttons({

    // onClick will be called any time the button is clicked
    onClick: function(data, actions) {

      // You must return a promise from onClick to do async validation
      return fetch('/my-api/validate', {
        method: 'post',
        headers: {
          'content-type': 'application/json'
        }
      }).then(function(res) {
        return res.json();
      }).then(function(data) {

        // If there is a validation error, reject, otherwise resolve
        if (data.validationError) {
          document.querySelector('#error').classList.remove('hidden');
          return actions.reject();
        } else {
          return actions.resolve();
        }
      });
    }

  }).render('#paypal-button-container');
</script>
```

**Comment by gilesbutler** [comment]
Great, thanks for the update @bluepnume 

Any idea on a rough eta for the next release?

Thanks

**Comment by bluepnume** [comment]
Docs are out at https://developer.paypal.com/docs/checkout/integration-features/validation/
