### ISSUE TITLE
Basic integration, checkout.js to SDK, transaction id..?

### ISSUE THREAD

**Issue by stephen-last** [paypal/paypal-smart-payment-buttons#4]
If this is the wrong place to post for help when trying to move our basic integration from `checkout.js` to `sdk/js` please point me in the right direction.

We're following these:

- https://developer.paypal.com/docs/checkout/integrate/
- https://developer.paypal.com/docs/checkout/reference/upgrade-integration/

We have the buttons rendering fine, and the transactions going through in the sandbox.

The issue we have is that the transaction id seems to be missing from the response.

Within `onApprove()` we're calling `actions.order.capture()` (and `actions.order.get()` seems to return the exact same response).

![ps](https://user-images.githubusercontent.com/16349203/53404038-b9732500-39ac-11e9-97cf-7e6390a9c010.jpg)

![ps2](https://user-images.githubusercontent.com/16349203/53404053-c1cb6000-39ac-11e9-9fe2-71c5d5285aae.jpg)

If we look at `purchase_units[0].payments.captures[0].id`, this seems to look like the transaction id, however, **it doesn't match the transaction id shown when we login to our account**!

With `checkout.js` we used `transactions[0].related_resources[0].sale.id` to obtain the transaction id.

We can't implement `sdk/js` without the transaction id as we use this to link transactions with orders in our systems.

Using the new `sdk/js` basic integration, how do we access the transaction id shown in the PayPal account..?

**Comment by CakeQ** [comment]
Adding onto this, there seems to be no way of checking for ECHECK payments within the output data, and quite a few other details listed on the SDK guide are also listed but not present in the return data.

**Comment by stephen-last** [comment]
Ok, we may have misunderstood something. 

It seems as though the payee (us) and the payer (customer) get a different transaction id.

The transaction id at `purchase_units[0].payments.captures[0].id` is the payee transaction id, which is fine. I was logging in to the payers account and seeing a different transaction id.
