### ISSUE TITLE
Calling actions.redirect() without passing a URL leads to: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by stephen-last** [paypal/paypal-smart-payment-buttons#6]
We're testing the new SDK integration and following the instructions here: https://developer.paypal.com/docs/checkout/integrate/

We're trying to use the `actions.redirect()` method within both `onApprove` and `onCancel` to redirect using the `application_context.return_url` and `application_context.cancel_url` setup when calling `actions.order.create()`.

The `application_context` object is documented here: https://developer.paypal.com/docs/api/orders/v2/#orders-create-request-body

This works when using `checkout.js`, but not when using the SDK.

Here is the complete one-page test we have:

```js
import '@babel/polyfill'

import express from 'express'
import bodyParser from 'body-parser'

const app = express()
app.use(bodyParser.urlencoded({ type: 'application/x-www-form-urlencoded', limit: '2mb', extended: true }))

const clientId = `123abc`

function homeHandler (req, res) {
  res.send(`
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>PayPal SDK</title>
    </head>
    <body>
      <div id="paypal-button-container"></div>
      <script src="https://www.paypal.com/sdk/js?currency=GBP&client-id=${clientId}"></script>
      <script>
      paypal.Buttons({
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: '0.01'
              }
            }],
            application_context: {
              return_url: '/success',
              cancel_url: '/cancelled'
            }
          })
        },
        onApprove: function(data, actions) {
          console.log('onApprove() data ===', data)
          return actions.order.capture().then(function(details) {
            console.log('onApprove() details ===', details)
            console.log('Transaction completed by ' + details.payer.name.given_name)
            actions.redirect()
          });
        },
        onCancel: function(data, actions) {
          console.log('onCancel() data ===', data); // {orderID: "123abc"}
          actions.redirect()
        },
        onError: function (error) {
          console.log('onError() error:', error)
        }
      }).render('#paypal-button-container')
      </script>
    </body>
    </html>
  `)
}

app.get('/', homeHandler)
app.get('/success', (req, res) => { res.send(`success`) })
app.get('/cancelled', (req, res) => { res.send(`cancelled`) })
app.get('/favicon.ico', (req, res) => { res.end() })

app.listen(7502, () => { console.log('http://localhost:7502') })
```

The error happens for both a normal test transaction (`onApprove`), and when we click to cancel the transaction (`onCancel`).

![ps](https://user-images.githubusercontent.com/16349203/53634010-f9d2dd00-3c10-11e9-8d7f-2cb79911a7b2.jpg)

This print-screen relates to clicking cancel, but the exact same thing happens when clicking buy/pay too. As you can see, we get:

> Uncaught TypeError: Cannot read property 'indexOf' of undefined

...and it tries to redirect to `http://localhost:7502/undefined`.

Removing the `actions.redirect()` calls removes all errors.

Can you confirm that this is a PayPal SDK bug..?

Can you provide any help on this as we can't implement the SDK as it stands..?

**Comment by stephen-last** [comment]
Ok, we can now see that `actions.redirect()` needs the URL passing to it, rather than it using a URL from the config passed to `actions.order.create({ ... })`.

This is mentioned on the [upgrade integration guide](https://developer.paypal.com/docs/checkout/reference/upgrade-integration/) at the very bottom, and we should've seen it there. However, for anyone following the [new integration guide](https://developer.paypal.com/docs/checkout/integrate/) they will be lead down the same path we were. That is, section 4 points to the Orders Create API reference, which lists `application_context` as something which can be passed to `actions.order.create({ ... })`, which has `return_url` and `cancel_url`.

Obviously two things would've helped here:

1. The SDK version needs to deal with nothing being passed in to `actions.redirect()`, instead of trying to redirect to `undefined`.
2. Documentation for data passed to, and returned from SDK methods, as per: https://github.com/paypal/paypal-smart-payment-buttons/issues/7

I will keep this issue open and rename it to cover point 1.

So...

Passing something other than a URL string to `actions.redirect()` should trigger an error with a descriptive message, and not try to redirect to `undefined`, or `null` etc.

**Comment by bluepnume** [comment]
Closing this for now. actions.redirect() will now fail with an appropriate error if nothing is passed. Please raise any new errors at https://github.com/paypal/paypal-checkout-components/issues
