### ISSUE TITLE
SDK convenience methods documentation

### ISSUE THREAD

**Issue by stephen-last** [paypal/paypal-smart-payment-buttons#7]
When trying to setup the SDK integration, the documentation doesn't seem to be complete. 

We're using this: https://developer.paypal.com/docs/checkout/integrate/

For example, in the **4. Set up the transaction** section is says:

> For the full list of parameters you can pass to actions.order.create() to set up the transaction, and example responses, see the Orders Create API reference.

Which points to: https://developer.paypal.com/docs/api/orders/v2/#orders_create

The problem is that we're not calling the orders api, the convenience method you provide is (`actions.order.create`) I assume.

So reading the orders api docs doesn't really help, because:

1. We can't change or add header parameters
2. We don't know which request body fields are being passed on
3. We don't get the full set of response fields

In the `actions.order.create` example, the response is just a string, which is the `id` (order id), we don't get `create_time`, `update_time`, `intent`, `payer`, `purchase_units`, or `status`.

```js
// currently
const orderId = actions.order.create({ ... })

// would be nice
const order = actions.order.create({ ... })
// { id, create_time, update_time, intent, payer, purchase_units, status }
```

We could do with documentation that clearly tells us the request and response fields for all the SDK convenience methods, as it's different from the request and response fields from the orders api.

- createOrder
  - `data`
  - `actions.order.create()`
- onApprove
  - `data`
  - `actions.order.capture()`
  - `actions.order.authorize()`
  - `actions.order.patch()`
  - `actions.order.get()`
  - `actions.redirect()`
  - `actions.restart()`
- onCancel
  - `data`
  - `actions.redirect()`

What are the parameters that these methods accept..?

What are the response fields for these methods..?

What are the fields on the `data` objects..?

**Comment by bluepnume** [comment]
We will be adding better api docs. For now I'm closing this; please raise any new issues at https://github.com/paypal/paypal-checkout-components/issues
