### ISSUE TITLE
Question about how the PayPal button is rendered...

### ISSUE THREAD

**Issue by sytong** [paypal/paypal-smart-payment-buttons#8]
I am just curious about this...

I read this line of code:

https://github.com/paypal/paypal-smart-payment-buttons/blob/f4fd5e8e982668f40397fe2e54dee962f601f845/server/button.js#L44

It looks like the PayPal button is server-side rendered but then why do we still need to call `render` in the integration code?

```
<body>
  <div id="paypal-button-container"></div>

  <script>
    paypal.Buttons().render('#paypal-button-container');
  </script>
</body>
```

**Comment by bluepnume** [comment]
It's rendered on both the client and the server, for performance reasons.
