### ISSUE TITLE
NPM clarification

### ISSUE THREAD

**Issue by nwallis** [paypal/paypal-smart-payment-buttons#9]
Hi.. 

I am integrating smart payment buttons with my website, but want an NPM module. I see that a bunch of other paypal libraries of offered up via NPM.   

Is this the same code as used on these buttons?

https://developer.paypal.com/docs/checkout/#try-the-buttons

**Comment by bluepnume** [comment]
No. We do not offer an npm library, since each script is custom-built for your site, with only the features you need.
